default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: argos_development

test:
  <<: *default
  database: argos_test

production:
  <<: *default
  database: argos_production
  username: argos
  password: <%= ENV['ARGOS_DATABASE_PASSWORD'] %>
